name : Readme checker

on:
  push:
    branches:
      - main


Jobs:
  readme-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build checker
        run : |
          ls -all