name : Readme checker

on:
  pull_request:
    branches:
      - main


jobs:
  readme-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build checker
        run : |
          ls -all